### ISSUE TITLE
EXDATE is not considered

### ISSUE THREAD

**Issue by ortwic** [Neuvernetzung/ts-ics#96]
It seems there is no property for excluded dates which is important for the recurrence rule.

```
BEGIN:VEVENT
CREATED:20240421T083326Z
LAST-MODIFIED:20240422T151909Z
DTSTAMP:20240422T151909Z
UID:e809c51a-0a11-40a9-8464-83fb6063d4ed
SUMMARY:Foo Bar
RRULE:FREQ=WEEKLY
EXDATE;TZID=Europe/Berlin:20240510T150000
EXDATE;TZID=Europe/Berlin:20240628T150000
DTSTART;TZID=Europe/Berlin:20240426T150000
DTEND;TZID=Europe/Berlin:20240427T000000
TRANSP:OPAQUE
SEQUENCE:3
X-MOZ-GENERATION:3
END:VEVENT
```

**Comment by timheerwagen** [comment]
Are you able to make a pull request for this? Otherwise I can take a look at it later.

**Comment by ortwic** [comment]
No, it's just a thing I stumbled across.

**Comment by EnzoReyes11** [comment]
Hi! I'm using ts-ics for a project I'm working on. EXDATE is one of the features on this calendar. 
For how we use this, I need to set have the type ExceptionDate exported, but it is not on the [npm dist ](https://www.npmjs.com/package/ts-ics?activeTab=code)

It might be because it is not exported explicitly on the [index](packages/ts-ics/src/types/index.ts)?

Thanks!

**Comment by timheerwagen** [comment]
Can you please explain your problem to me with a concrete example, as I don't quite understand where your problem lies.

`exceptionDates?: ExceptionDates` is part of the VEvent Type
